version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - docker-kafka-zookeeper-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "/bin/kafka-topics --list --bootstrap-server localhost:9092"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - docker-kafka-app-network
      - docker-kafka-zookeeper-network
      
  db:
    image: postgres:13.1-alpine
    container_name: db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "psql -U compose-postgres -c '\\x' -c '\\dt+;'"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: compose-postgres
      POSTGRES_PASSWORD: compose-postgres-password
    networks:
      - docker-postgresql-network

networks:
  docker-kafka-app-network:
    driver: bridge
  docker-kafka-zookeeper-network:
    driver: bridge
  docker-postgresql-network:
    driver: bridge
